In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# dta = pd.read_stata('CS_S10A1_A2_credits.dta')
df = pd.read_csv('CS_S10A1_A2_credits.csv')

In [3]:
df.head()

,Unnamed: 0,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,...,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
0,0,300001.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,Yes,Insuffivient income,Yes,...,Borrowed from relative,Business expansion,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
1,1,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Mokash,Purchase of household items,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
2,2,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
3,3,300003.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
4,4,300004.0,10001.0,City of Kigali,Nyarugenge,Urban,NaN,No,NaN,No,...,NaN,NaN,NaN,NaN,111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor

In [4]:
df = df.drop(columns=["Unnamed: 0"])

In [96]:
df.describe(include='all')

,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,s10aq4,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
count,20509.000000,20509.000000,20509,20509,20509,15770.000000,20509,1225,20509,15770.000000,15770,15770,1712,15770,20509.000000,20509.000000,20509,20509,20509,20509
unique,NaN,NaN,5,30,2,NaN,2,5,2,NaN,12,11,4,3,NaN,NaN,5,2,3,2
top,NaN,NaN,Southern,Ruhango,Rural,NaN,No,Unclear purpose of the loan,Yes,NaN,Tontine (community),Food purchase,Land,No,NaN,NaN,Mid/upper,Non Poor,Non Poor,Non Extreme Poor
freq,NaN,NaN,5601,1103,15389,NaN,19284,319,15770,NaN,7797,5372,1276,5766,NaN,NaN,4491,15648,15648,19668
mean,307477.323126,10832.236140,NaN,NaN,NaN,1.421623,NaN,NaN,NaN,1.513887,NaN,NaN,NaN,NaN,347.384953,216.849669,NaN,NaN,NaN,NaN
std,4254.644418,473.034498,NaN,NaN,NaN,0.651911,NaN,NaN,NaN,0.900302,NaN,NaN,NaN,NaN,135.595772,57.840878,NaN,NaN,NaN,NaN
min,300001.000000,10001.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,111.000000,48.838065,NaN,NaN,NaN,NaN
25%,303889.000000,10433.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,251.000000,183.525034,NaN,NaN,NaN,NaN
50%,307440.000000,10828.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,342.000000,199.916163,NaN,NaN,NaN,NaN
75%,311134.000000,11239.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,442.000000,239.678679,NaN,NaN,NaN,NaN
max,315054.000000,11674.000000,NaN,NaN,NaN,12.000000,NaN,NaN,NaN,11.000000,NaN,NaN,NaN,NaN,572.000000,626.651181,NaN,NaN,NaN,NaN

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20509 entries, 0 to 20508
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   hhid       20509 non-null  float64
 1   clust      20509 non-null  float64
 2   province   20509 non-null  object
 3   district   20509 non-null  object
 4   ur         20509 non-null  object
 5   pid        15770 non-null  float64
 6   s10aq1     20509 non-null  object
 7   s10aq2     1225 non-null   object
 8   s10aq3     20509 non-null  object
 9   s10aq4     15770 non-null  float64
 10  s10aq6     15770 non-null  object
 11  s10aq7     15770 non-null  object
 12  s10aq8     1712 non-null   object
 13  s10aq9     15770 non-null  object
 14  strata_id  20509 non-null  int64
 15  weight     20509 non-null  float64
 16  quintile   20509 non-null  object
 17  pov_jan    20509 non-null  object
 18  poverty    20509 non-null  object
 19  epov_jan   20509 non-null  object
dtypes: float64(5), int64(1), object(14)
memory usage: 3.1+ MB

In [100]:
df_sum = df.isna().sum()
df_average = df.isna().mean()

print(f"The sum of missing values is {df_sum}")
print(f"The average of missing values is {df_average}")

The sum of missing values is hhid             0
clust            0
province         0
district         0
ur               0
pid           4739
s10aq1           0
s10aq2       19284
s10aq3           0
s10aq4        4739
s10aq6        4739
s10aq7        4739
s10aq8       18797
s10aq9        4739
strata_id        0
weight           0
quintile         0
pov_jan          0
poverty          0
epov_jan         0
dtype: int64
The average of missing values is hhid         0.000000
clust        0.000000
province     0.000000
district     0.000000
ur           0.000000
pid          0.231069
s10aq1       0.000000
s10aq2       0.940270
s10aq3       0.000000
s10aq4       0.231069
s10aq6       0.231069
s10aq7       0.231069
s10aq8       0.916524
s10aq9       0.231069
strata_id    0.000000
weight       0.000000
quintile     0.000000
pov_jan      0.000000
poverty      0.000000
epov_jan     0.000000
dtype: float64

In [101]:
df2 = df.drop(['hhid', 'clust', 'pid', 's10aq4', 's10aq6', 's10aq7', 's10aq8', 's10aq9', 'strata_id', 'weight', 'pov_jan', 'epov_jan'], axis='columns')
df2.head()

,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty
0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor
1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor

In [102]:
df.poverty.unique()

array(['Non Poor', 'Moderately poor', 'Severaly Poor'], dtype=object)

In [103]:
# Assign numerical value to each category

df2['poverty_converted'] = df2.poverty.str.strip().str.lower().map({
    "non poor": 2,
    "moderately poor": 1,
    "severaly poor": 0,
})

In [104]:
df2['s10aq1_converted'] = df2.s10aq1.apply(lambda x: 1 if x == 'Yes' else 0)
df2.head()

,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted
0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor,2,1
1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,2,0
2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,2,0
3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,2,0
4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor,2,0

In [105]:
# compute class imbalance

counts = df2['s10aq1_converted'].value_counts()
print(counts)

s10aq1_converted
0    19284
1     1225
Name: count, dtype: int64

In [106]:
majority = counts.max()
minority = counts.min()

imbalance = majority / minority
print(f"Imbalance ration {imbalance}") # how cone class appear much more than another

Imbalance ration 15.742040816326531

In [107]:
df3 = df2.drop('s10aq2', axis='columns')
df3.head()

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0
3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0
4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,2,0

In [108]:
# Data cleaning cont..
df3['s10aq3_converted'] = df3.s10aq3.apply(lambda x: 1 if x == 'Yes' else 0)
df3.head(3)

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted,s10aq3_converted
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1,1
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1

In [149]:
# On hot encoder for province and district

dummies = pd.get_dummies(df3.province).astype(int)
dummies.head()

   City of Kigali  Eastern  Northern  Southern  Western
0               1        0         0         0        0
1               1        0         0         0        0
2               1        0         0         0        0
3               1        0         0         0        0
4               1        0         0         0        0

In [150]:
df4 = pd.concat([df3, dummies], axis='columns')
df4.head()

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1,1,1,0,0,0,0
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,1,0,0,0,0
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,1,0,0,0,0
3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,1,0,0,0,0
4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,2,0,0,1,0,0,0,0

In [151]:
district_dummies = pd.get_dummies(df4.district).astype(int)
district_dummies.head()

df5 = pd.concat([df4, district_dummies], axis='columns')
df5.head(3)

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted,s10aq3_converted,...,Nyamasheke,Nyanza,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1,1,...,0,0,1,0,0,0,0,0,0,0
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,0,0,1,0,0,0,0,0,0,0
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,0,0,1,0,0,0,0,0,0,0

In [152]:
df5['ur_converted'] = df5.ur.apply(lambda x: 1 if x == 'Urban' else 0)
df5.head(3)

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted,s10aq3_converted,...,Nyanza,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1,1,...,0,1,0,0,0,0,0,0,0,1
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,0,1,0,0,0,0,0,0,0,1
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,0,1,0,0,0,0,0,0,0,1

In [153]:
df5.quintile.unique().sum()

'UpperMidMid/upperPoor/midPoor'

In [154]:
# Assign numerical value to each category

df5['quintile_converted'] = df5.quintile.str.strip().str.lower().map({
    "poor": 0,
    "poor/mid": 0.5,
    "mid": 1,
    "mid/upper": 1.5,
    "upper": 2
})

In [155]:
df5.quintile_converted.value_counts()

quintile_converted
1.5    4491
1.0    4334
2.0    4281
0.5    3974
0.0    3429
Name: count, dtype: int64

In [156]:
df5.head()

,province,district,ur,s10aq1,s10aq3,quintile,poverty,poverty_converted,s10aq1_converted,s10aq3_converted,...,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,quintile_converted
0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,2,1,1,...,1,0,0,0,0,0,0,0,1,2.0
1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,1,0,0,0,0,0,0,0,1,2.0
2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,1,0,0,0,0,0,0,0,1,2.0
3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,2,0,1,...,1,0,0,0,0,0,0,0,1,2.0
4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,2,0,0,...,1,0,0,0,0,0,0,0,1,2.0

In [157]:
df6 = df5.drop(['province', 'district', 'ur', 's10aq1', 's10aq3', 'poverty'], axis='columns')
df6.head()

,quintile,poverty_converted,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western,Bugesera,...,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,quintile_converted
0,Upper,2,1,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
1,Upper,2,0,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
2,Upper,2,0,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
3,Upper,2,0,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
4,Upper,2,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0

In [158]:
df7 = df6.drop('quintile', axis='columns')
df7.head()

,poverty_converted,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western,Bugesera,Burera,...,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,quintile_converted
0,2,1,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
1,2,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
2,2,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
3,2,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0
4,2,0,0,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,2.0

In [159]:
X = df7.drop('s10aq1_converted', axis='columns')
y = df7.s10aq1_converted

In [160]:
from sklearn.model_selection import train_test_split
# temp contain validation + test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Training data {X_train.shape, y_train.shape}")
print(f"Testing data {X_test.shape, y_test.shape}")
print(f"Validating data {X_val.shape, y_val.shape}")

Training data ((14356, 39), (14356,))
Testing data ((3077, 39), (3077,))
Validating data ((3076, 39), (3076,))

In [161]:
df7.s10aq1_converted.value_counts()

s10aq1_converted
0    19284
1     1225
Name: count, dtype: int64

In [162]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (2.3.4)
Requirement already satisfied: scipy<2,>=1.11.4 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (3.6.0)

In [122]:
# handling imbalance problem
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

y_train_smote.value_counts()

s10aq1_converted
0    13499
1    13499
Name: count, dtype: int64

In [123]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train_res, y_train_res)

y_pred = model.predict(X_val)
model.score(X_val, y_val)

0.8972691807542262

In [124]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, classification_report

print("Accuracy score", accuracy_score(y_val, y_pred))
print("F1 socre", f1_score(y_val, y_pred))
print("precision score", precision_score(y_val, y_pred))

Accuracy score 0.8972691807542262
F1 socre 0.18134715025906736
precision score 0.17326732673267325

In [125]:
print("Classification report", classification_report(y_val, y_pred))

Classification report               precision    recall  f1-score   support

           0       0.95      0.94      0.95      2892
           1       0.17      0.19      0.18       184

    accuracy                           0.90      3076
   macro avg       0.56      0.57      0.56      3076
weighted avg       0.90      0.90      0.90      3076

In [126]:
confusion_matrix(y_val, y_pred)

array([[2725,  167],
       [ 149,   35]])

In [127]:
y_pred_proba = model.predict_proba(X_test)[:, 1]
y_proba = model.predict_proba(X_test)

y_pred_new = (y_pred_proba > 0.3).astype(int)

In [128]:
confusion_matrix(y_test, y_pred_new)

array([[1508, 1385],
       [  64,  120]])

In [129]:
print("Classification report", classification_report(y_test, y_pred_new))

Classification report               precision    recall  f1-score   support

           0       0.96      0.52      0.68      2893
           1       0.08      0.65      0.14       184

    accuracy                           0.53      3077
   macro avg       0.52      0.59      0.41      3077
weighted avg       0.91      0.53      0.64      3077

In [130]:
from imblearn.under_sampling import RandomUnderSampler

sampler = RandomUnderSampler(sampling_strategy=0.5, random_state=42)
X_train_res, y_train_res = sampler.fit_resample(X_train, y_train)

In [131]:
y_train_res.value_counts()

s10aq1_converted
0    1714
1     857
Name: count, dtype: int64

In [132]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(random_state=42)

rf_model.fit(X_train_res, y_train_res)

rf_model.score(X_test, y_test)

0.812804679883003

In [133]:
rf_pred = rf_model.predict(X_test)

print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.95      0.84      0.89      2893
           1       0.13      0.36      0.19       184

    accuracy                           0.81      3077
   macro avg       0.54      0.60      0.54      3077
weighted avg       0.90      0.81      0.85      3077

In [134]:
confusion_matrix(y_test, rf_pred)

array([[2435,  458],
       [ 118,   66]])

In [163]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators = 300,
    max_depth=4,
    learning_rate=0.05,
    scale_pos_weight= (2893/184),  # IMPORTANT
    random_state=42
)

xgb_model.fit(X_train_res, y_train_res)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

In [164]:
y_pred = xgb_model.predict(X_test)
xgb_model.score(X_test, y_pred)

1.0

In [165]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.08      0.15      2893
           1       0.06      0.98      0.12       184

    accuracy                           0.14      3077
   macro avg       0.52      0.53      0.13      3077
weighted avg       0.93      0.14      0.15      3077

In [148]:
xgb_model.feature_importances_

array([0.02028192, 0.03050514, 0.02752226, 0.05572543, 0.02777904,
       0.03875649, 0.05691447, 0.01058581, 0.        , 0.02958323,
       0.02832206, 0.02579786, 0.01083319, 0.01486597, 0.05435976,
       0.01262657, 0.02551105, 0.03297487, 0.02314094, 0.01635618,
       0.01404891, 0.02425368, 0.02411687, 0.0452306 , 0.04408473,
       0.02025663, 0.02973961, 0.01331947, 0.01482022, 0.0050951 ,
       0.0182403 , 0.07122181, 0.0396808 , 0.01082623, 0.01459685,
       0.01244842, 0.01586348, 0.01799699, 0.02171709], dtype=float32)

In [167]:
def predict_credit_denial(district, province, s10aq3_converted, ur_converted, poverty_converted, quintile_converted): 
    district_index = np.where(X.columns == district)[0][0]
    province_index = np.where(X.columns == province)[0][0]
    quintile_index = np.where(X.columns == "quintile_converted")[0][0]
    poverity_index = np.where(X.columns == "poverty_converted")[0][0]
    s10aq3_index = np.where(X.columns == "s10aq3_converted")[0][0]
    ur_index = np.where(X.columns == "ur_converted")[0][0]

    x = np.zeros(len(X.columns))

    x[s10aq3_index] = s10aq3_converted
    x[ur_index] = ur_converted
    x[quintile_index] = quintile_converted
    x[poverity_index] = poverty_converted

    if (district_index >= 0):
        x[district_index] = 1
        
    if (province_index >= 0):
        x[province_index] = 1
        
    y_pred = xgb_model.predict([x])[0]
    proba = xgb_model.predict_proba([x])[0]

    return y_pred, proba

predict_credit_denial('Bugesera', 'Eastern', 0, 1, 1, 2)

(np.int64(1), array([0.14707959, 0.8529204 ], dtype=float32))

In [168]:
import pickle

with open('model.pickle', 'wb') as f:
    pickle.load(f)