In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# dta = pd.read_stata('CS_S10A1_A2_credits.dta')
df = pd.read_csv('CS_S10A1_A2_credits.csv')

In [3]:
df.head()

,Unnamed: 0,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,...,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
0,0,300001.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,Yes,Insuffivient income,Yes,...,Borrowed from relative,Business expansion,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
1,1,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Mokash,Purchase of household items,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
2,2,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
3,3,300003.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
4,4,300004.0,10001.0,City of Kigali,Nyarugenge,Urban,NaN,No,NaN,No,...,NaN,NaN,NaN,NaN,111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor

In [4]:
df.describe(include='all')

,Unnamed: 0,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,...,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
count,20509.000000,20509.000000,20509.000000,20509,20509,20509,15770.000000,20509,1225,20509,...,15770,15770,1712,15770,20509.000000,20509.000000,20509,20509,20509,20509
unique,NaN,NaN,NaN,5,30,2,NaN,2,5,2,...,12,11,4,3,NaN,NaN,5,2,3,2
top,NaN,NaN,NaN,Southern,Ruhango,Rural,NaN,No,Unclear purpose of the loan,Yes,...,Tontine (community),Food purchase,Land,No,NaN,NaN,Mid/upper,Non Poor,Non Poor,Non Extreme Poor
freq,NaN,NaN,NaN,5601,1103,15389,NaN,19284,319,15770,...,7797,5372,1276,5766,NaN,NaN,4491,15648,15648,19668
mean,10254.000000,307477.323126,10832.236140,NaN,NaN,NaN,1.421623,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,347.384953,216.849669,NaN,NaN,NaN,NaN
std,5920.582671,4254.644418,473.034498,NaN,NaN,NaN,0.651911,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,135.595772,57.840878,NaN,NaN,NaN,NaN
min,0.000000,300001.000000,10001.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,111.000000,48.838065,NaN,NaN,NaN,NaN
25%,5127.000000,303889.000000,10433.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.000000,183.525034,NaN,NaN,NaN,NaN
50%,10254.000000,307440.000000,10828.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,342.000000,199.916163,NaN,NaN,NaN,NaN
75%,15381.000000,311134.000000,11239.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,442.000000,239.678679,NaN,NaN,NaN,NaN
max,20508.000000,315054.000000,11674.000000,NaN,NaN,NaN,12.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,572.000000,626.651181,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20509 entries, 0 to 20508
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20509 non-null  int64
 1   hhid        20509 non-null  float64
 2   clust       20509 non-null  float64
 3   province    20509 non-null  object
 4   district    20509 non-null  object
 5   ur          20509 non-null  object
 6   pid         15770 non-null  float64
 7   s10aq1      20509 non-null  object
 8   s10aq2      1225 non-null   object
 9   s10aq3      20509 non-null  object
 10  s10aq4      15770 non-null  float64
 11  s10aq6      15770 non-null  object
 12  s10aq7      15770 non-null  object
 13  s10aq8      1712 non-null   object
 14  s10aq9      15770 non-null  object
 15  strata_id   20509 non-null  int64
 16  weight      20509 non-null  float64
 17  quintile    20509 non-null  object
 18  pov_jan     20509 non-null  object
 19  poverty     20509 non-null  object
 20  epov_jan    20509 non-null  object
dtypes: float64(5), int64(2), object(14)
memory usage: 3.3+ MB

In [6]:
df_sum = df.isna().sum()
df_average = df.isna().mean()

print(f"The sum of missing values is {df_sum}")
print(f"The average of missing values is {df_average}")

The sum of missing values is Unnamed: 0        0
hhid              0
clust             0
province          0
district          0
ur                0
pid            4739
s10aq1            0
s10aq2        19284
s10aq3            0
s10aq4         4739
s10aq6         4739
s10aq7         4739
s10aq8        18797
s10aq9         4739
strata_id         0
weight            0
quintile          0
pov_jan           0
poverty           0
epov_jan          0
dtype: int64
The average of missing values is Unnamed: 0    0.000000
hhid          0.000000
clust         0.000000
province      0.000000
district      0.000000
ur            0.000000
pid           0.231069
s10aq1        0.000000
s10aq2        0.940270
s10aq3        0.000000
s10aq4        0.231069
s10aq6        0.231069
s10aq7        0.231069
s10aq8        0.916524
s10aq9        0.231069
strata_id     0.000000
weight        0.000000
quintile      0.000000
pov_jan       0.000000
poverty       0.000000
epov_jan      0.000000
dtype: float64

In [7]:
df2 = df.drop(['hhid', 'clust', 'pid', 's10aq4', 's10aq6', 's10aq7', 's10aq8', 's10aq9', 'strata_id', 'weight', 'pov_jan', 'epov_jan'], axis='columns')
df2.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty
0,0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor
1,1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
2,2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
3,3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
4,4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor

In [8]:
df2['s10aq1_converted'] = df2.s10aq1.apply(lambda x: 1 if x == 'Yes' else 0)
df2.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty,s10aq1_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor,1
1,1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
2,2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
3,3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
4,4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor,0

In [9]:
# compute class imbalance

counts = df2['s10aq1_converted'].value_counts()
print(counts)

s10aq1_converted
0    19284
1     1225
Name: count, dtype: int64

In [10]:
majority = counts.max()
minority = counts.min()

imbalance = majority / minority
print(f"Imbalance ration {imbalance}") # how cone class appear much more than another

Imbalance ration 15.742040816326531

In [11]:
df3 = df2.drop('s10aq2', axis='columns')
df3.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
3,3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
4,4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,0

In [12]:
# Data cleaning cont..
df3['s10aq3_converted'] = df3.s10aq3.apply(lambda x: 1 if x == 'Yes' else 0)
df3.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1

In [13]:
# On hot encoder for province and district

dummies = pd.get_dummies(df3.province).astype(int)
dummies.head()

   City of Kigali  Eastern  Northern  Southern  Western
0               1        0         0         0        0
1               1        0         0         0        0
2               1        0         0         0        0
3               1        0         0         0        0
4               1        0         0         0        0

In [14]:
df4 = pd.concat([df3, dummies], axis='columns')
df4.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,1,0,0,0,0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
3,3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
4,4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,0,0,1,0,0,0,0

In [15]:
district_dummies = pd.get_dummies(df4.district).astype(int)
district_dummies.head()

df5 = pd.concat([df4, district_dummies], axis='columns')
df5.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,...,Nyamasheke,Nyanza,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,...,0,0,1,0,0,0,0,0,0,0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,1,0,0,0,0,0,0,0

In [16]:
df5['ur_converted'] = df5.ur.apply(lambda x: 1 if x == 'Urban' else 0)
df5.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,...,Nyanza,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,...,0,1,0,0,0,0,0,0,0,1
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,1,0,0,0,0,0,0,0,1
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,1,0,0,0,0,0,0,0,1

In [17]:
df5['poverty_converted'] = df5.ur.apply(lambda x: 1 if x == 'Poor' else 0)
df5.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,...,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,poverty_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,...,1,0,0,0,0,0,0,0,1,0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,1,0,0,0,0,0,0,0,1,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,1,0,0,0,0,0,0,0,1,0

In [18]:
df5.quintile.unique().sum()

'UpperMidMid/upperPoor/midPoor'

In [19]:
# Assign numerical value to each category

df5['quintile_converted'] = df5.quintile.str.strip().str.lower().map({
    "poor": 0,
    "poor/mid": 0.5,
    "mid": 1,
    "mid/upper": 1.5,
    "upper": 2
})

In [20]:
df5.quintile_converted.value_counts()

quintile_converted
1.5    4491
1.0    4334
2.0    4281
0.5    3974
0.0    3429
Name: count, dtype: int64

In [21]:
df5.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,...,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,poverty_converted,quintile_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,...,0,0,0,0,0,0,0,1,0,2.0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,0,0,0,0,0,1,0,2.0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,0,0,0,0,0,1,0,2.0
3,3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,0,0,0,0,0,1,0,2.0
4,4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,0,0,...,0,0,0,0,0,0,0,1,0,2.0

In [22]:
df6 = df5.drop(['province', 'district', 'ur', 's10aq1', 's10aq3', 'poverty'], axis='columns')
df6.head()

,Unnamed: 0,quintile,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western,Bugesera,...,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,poverty_converted,quintile_converted
0,0,Upper,1,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
1,1,Upper,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
2,2,Upper,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
3,3,Upper,0,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
4,4,Upper,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0

In [23]:
df7 = df6.drop('quintile', axis='columns')
df7.head()

,Unnamed: 0,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western,Bugesera,Burera,...,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana,ur_converted,poverty_converted,quintile_converted
0,0,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
1,1,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
2,2,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
3,3,0,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0
4,4,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,2.0

In [24]:
X = df7.drop('s10aq1_converted', axis='columns')
y = df7.s10aq1_converted

In [25]:
from sklearn.model_selection import train_test_split
# temp contain validation + test
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print(f"Training data {X_train.shape, y_train.shape}")
print(f"Testing data {X_test.shape, y_test.shape}")
print(f"Validating data {X_val.shape, y_val.shape}")

Training data ((14356, 40), (14356,))
Testing data ((3077, 40), (3077,))
Validating data ((3076, 40), (3076,))

In [46]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight='balanced', max_iter=5000, solver='lbfgs')

# model.fit(X_train, y_train)
# model.score(X_val, y_val)

In [27]:
!pip install imbalanced-learn

Requirement already satisfied: imbalanced-learn in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (0.14.1)
Requirement already satisfied: numpy<3,>=1.25.2 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (2.3.4)
Requirement already satisfied: scipy<2,>=1.11.4 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.16.3)
Requirement already satisfied: scikit-learn<2,>=1.4.2 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.8.0)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (0.1.5)
Requirement already satisfied: joblib<2,>=1.2.0 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (1.5.3)
Requirement already satisfied: threadpoolctl<4,>=2.0.0 in /home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages (from imbalanced-learn) (3.6.0)

In [43]:
# handling imbalance problem
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

y_slamped.value_counts

<bound method IndexOpsMixin.value_counts of 0        0
1        0
2        0
3        0
4        0
        ..
26993    1
26994    1
26995    1
26996    1
26997    1
Name: s10aq1_converted, Length: 26998, dtype: int64>

In [47]:
model.fit(X_train_smote, y_train_smote)

/home/etiene-niyomugabo123/miniconda3/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 5000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=5000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(class_weight='balanced', max_iter=5000)

In [49]:
y_val_pred = model.predict(X_val)
y_val_pred_prob = model.predict_proba(X_val)

In [50]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, confusion_matrix, classification_report

print("Accuracy score", accuracy_score(y_val, y_val_pred))
print("F1 socre", f1_score(y_val, y_val_pred))
print("precision score", precision_score(y_val, y_val_pred))

Accuracy score 0.6176853055916776
F1 socre 0.14285714285714285
precision score 0.08249158249158249

In [51]:
print("Classification report", classification_report(y_val, y_val_pred))

Classification report               precision    recall  f1-score   support

           0       0.95      0.62      0.75      2892
           1       0.08      0.53      0.14       184

    accuracy                           0.62      3076
   macro avg       0.52      0.58      0.45      3076
weighted avg       0.90      0.62      0.72      3076

In [53]:
confusion_matrix(y_val, y_val_pred)

array([[1802, 1090],
       [  86,   98]])

In [55]:
y_val_new = (y_val_pred_prob[:, 1] < 0.6).astype(int)

print(classification_report(y_val, y_val_new))

              precision    recall  f1-score   support

           0       0.88      0.15      0.26      2892
           1       0.05      0.67      0.09       184

    accuracy                           0.18      3076
   macro avg       0.46      0.41      0.17      3076
weighted avg       0.83      0.18      0.25      3076

In [65]:
# lets try random forest

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators = 500,
    class_weight = 'balanced',
    random_state = 42
)

In [66]:
rf.fit(X_train_smote, y_train_smote)

rf_y_val_pred = rf.predict(X_val)

In [67]:
print(classification_report(y_val, rf_y_val_pred))

              precision    recall  f1-score   support

           0       0.97      0.94      0.95      2892
           1       0.34      0.50      0.41       184

    accuracy                           0.91      3076
   macro avg       0.66      0.72      0.68      3076
weighted avg       0.93      0.91      0.92      3076

In [68]:
confusion_matrix(y_val, rf_y_val_pred)

array([[2717,  175],
       [  92,   92]])

In [72]:
rf.score(X_test, y_test)

0.9047773805654858