In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
# dta = pd.read_stata('CS_S10A1_A2_credits.dta')
df = pd.read_csv('CS_S10A1_A2_credits.csv')

In [19]:
df.head()

,Unnamed: 0,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,...,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
0,0,300001.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,Yes,Insuffivient income,Yes,...,Borrowed from relative,Business expansion,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
1,1,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Mokash,Purchase of household items,NaN,"Yes, part",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
2,2,300002.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
3,3,300003.0,10001.0,City of Kigali,Nyarugenge,Urban,1.0,No,NaN,Yes,...,Borrowed from relative,Food purchase,NaN,"Yes, all",111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor
4,4,300004.0,10001.0,City of Kigali,Nyarugenge,Urban,NaN,No,NaN,No,...,NaN,NaN,NaN,NaN,111,170.958195,Upper,Non Poor,Non Poor,Non Extreme Poor

In [26]:
df.describe(include='all')

,Unnamed: 0,hhid,clust,province,district,ur,pid,s10aq1,s10aq2,s10aq3,...,s10aq6,s10aq7,s10aq8,s10aq9,strata_id,weight,quintile,pov_jan,poverty,epov_jan
count,20509.000000,20509.000000,20509.000000,20509,20509,20509,15770.000000,20509,1225,20509,...,15770,15770,1712,15770,20509.000000,20509.000000,20509,20509,20509,20509
unique,NaN,NaN,NaN,5,30,2,NaN,2,5,2,...,12,11,4,3,NaN,NaN,5,2,3,2
top,NaN,NaN,NaN,Southern,Ruhango,Rural,NaN,No,Unclear purpose of the loan,Yes,...,Tontine (community),Food purchase,Land,No,NaN,NaN,Mid/upper,Non Poor,Non Poor,Non Extreme Poor
freq,NaN,NaN,NaN,5601,1103,15389,NaN,19284,319,15770,...,7797,5372,1276,5766,NaN,NaN,4491,15648,15648,19668
mean,10254.000000,307477.323126,10832.236140,NaN,NaN,NaN,1.421623,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,347.384953,216.849669,NaN,NaN,NaN,NaN
std,5920.582671,4254.644418,473.034498,NaN,NaN,NaN,0.651911,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,135.595772,57.840878,NaN,NaN,NaN,NaN
min,0.000000,300001.000000,10001.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,111.000000,48.838065,NaN,NaN,NaN,NaN
25%,5127.000000,303889.000000,10433.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,251.000000,183.525034,NaN,NaN,NaN,NaN
50%,10254.000000,307440.000000,10828.000000,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,342.000000,199.916163,NaN,NaN,NaN,NaN
75%,15381.000000,311134.000000,11239.000000,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,442.000000,239.678679,NaN,NaN,NaN,NaN
max,20508.000000,315054.000000,11674.000000,NaN,NaN,NaN,12.000000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,572.000000,626.651181,NaN,NaN,NaN,NaN

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20509 entries, 0 to 20508
Data columns (total 21 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  20509 non-null  int64
 1   hhid        20509 non-null  float64
 2   clust       20509 non-null  float64
 3   province    20509 non-null  object
 4   district    20509 non-null  object
 5   ur          20509 non-null  object
 6   pid         15770 non-null  float64
 7   s10aq1      20509 non-null  object
 8   s10aq2      1225 non-null   object
 9   s10aq3      20509 non-null  object
 10  s10aq4      15770 non-null  float64
 11  s10aq6      15770 non-null  object
 12  s10aq7      15770 non-null  object
 13  s10aq8      1712 non-null   object
 14  s10aq9      15770 non-null  object
 15  strata_id   20509 non-null  int64
 16  weight      20509 non-null  float64
 17  quintile    20509 non-null  object
 18  pov_jan     20509 non-null  object
 19  poverty     20509 non-null  object
 20  epov_jan    20509 non-null  object
dtypes: float64(5), int64(2), object(14)
memory usage: 3.3+ MB

In [27]:
df_sum = df.isna().sum()
df_average = df.isna().mean()

print(f"The sum of missing values is {df_sum}")
print(f"The average of missing values is {df_average}")

The sum of missing values is Unnamed: 0        0
hhid              0
clust             0
province          0
district          0
ur                0
pid            4739
s10aq1            0
s10aq2        19284
s10aq3            0
s10aq4         4739
s10aq6         4739
s10aq7         4739
s10aq8        18797
s10aq9         4739
strata_id         0
weight            0
quintile          0
pov_jan           0
poverty           0
epov_jan          0
dtype: int64
The average of missing values is Unnamed: 0    0.000000
hhid          0.000000
clust         0.000000
province      0.000000
district      0.000000
ur            0.000000
pid           0.231069
s10aq1        0.000000
s10aq2        0.940270
s10aq3        0.000000
s10aq4        0.231069
s10aq6        0.231069
s10aq7        0.231069
s10aq8        0.916524
s10aq9        0.231069
strata_id     0.000000
weight        0.000000
quintile      0.000000
pov_jan       0.000000
poverty       0.000000
epov_jan      0.000000
dtype: float64

In [30]:
df2 = df.drop(['hhid', 'clust', 'pid', 's10aq4', 's10aq6', 's10aq7', 's10aq8', 's10aq9', 'strata_id', 'weight', 'pov_jan', 'epov_jan'], axis='columns')
df2.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty
0,0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor
1,1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
2,2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
3,3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor
4,4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor

In [33]:
df2['s10aq1_converted'] = df2.s10aq1.apply(lambda x: 1 if x == 'Yes' else 0)
df2.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq2,s10aq3,quintile,poverty,s10aq1_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Insuffivient income,Yes,Upper,Non Poor,1
1,1,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
2,2,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
3,3,City of Kigali,Nyarugenge,Urban,No,NaN,Yes,Upper,Non Poor,0
4,4,City of Kigali,Nyarugenge,Urban,No,NaN,No,Upper,Non Poor,0

In [35]:
# compute class imbalance

counts = df2['s10aq1_converted'].value_counts()
print(counts)

s10aq1_converted
0    19284
1     1225
Name: count, dtype: int64

In [38]:
majority = counts.max()
minority = counts.min()

imbalance = majority / minority
print(f"Imbalance ration {imbalance}") # how cone class appear much more than another

Imbalance ration 15.742040816326531

In [40]:
df3 = df2.drop('s10aq2', axis='columns')
df3.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
3,3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0
4,4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,0

In [41]:
# Data cleaning cont..
df3['s10aq3_converted'] = df3.s10aq3.apply(lambda x: 1 if x == 'Yes' else 0)
df3.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1

In [42]:
# On hot encoder for province and district

dummies = pd.get_dummies(df3.province).astype(int)
dummies.head()

   City of Kigali  Eastern  Northern  Southern  Western
0               1        0         0         0        0
1               1        0         0         0        0
2               1        0         0         0        0
3               1        0         0         0        0
4               1        0         0         0        0

In [45]:
df4 = pd.concat([df3, dummies], axis='columns')
df4.head()

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,City of Kigali,Eastern,Northern,Southern,Western
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,1,0,0,0,0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
3,3,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,1,0,0,0,0
4,4,City of Kigali,Nyarugenge,Urban,No,No,Upper,Non Poor,0,0,1,0,0,0,0

In [48]:
district_dummies = pd.get_dummies(df4.district).astype(int)
district_dummies.head()

df5 = pd.concat([df4, district_dummies], axis='columns')
df5.head(3)

,Unnamed: 0,province,district,ur,s10aq1,s10aq3,quintile,poverty,s10aq1_converted,s10aq3_converted,...,Nyamasheke,Nyanza,Nyarugenge,Nyaruguru,Rubavu,Ruhango,Rulindo,Rusizi,Rutsiro,Rwamagana
0,0,City of Kigali,Nyarugenge,Urban,Yes,Yes,Upper,Non Poor,1,1,...,0,0,1,0,0,0,0,0,0,0
1,1,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,1,0,0,0,0,0,0,0
2,2,City of Kigali,Nyarugenge,Urban,No,Yes,Upper,Non Poor,0,1,...,0,0,1,0,0,0,0,0,0,0

In [ ]:
# handling imbalance problem
from imblearn.under_sampling import SMOTE